[package]
name = "atlas-local"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

include = [
    "src/**",
    "Cargo.toml",
    "README.md",
    "CONTRIBUTING.md",
    "LICENSE",
    "license.html",
]

[features]
e2e-tests = []

[dependencies]
bollard = "0.19.2"
futures-util = "0.3.31"
maplit = "1.0.2"
rand = "0.9.2"
semver = "1.0.26"
thiserror = "2.0.16"
tokio = { version = "1.0", features = ["time"] }

[dev-dependencies]
anyhow = "1.0.99"
mockall = "0.13.1"
pretty_assertions = "1.4.1"
tokio = { version = "1.0", features = ["full"] }
